from lux.game_constants import GAME_CONSTANTS


NONE = 0
NORTH = 1
EAST = 2
SOUTH = 3
WEST = 4

MOVEMENT_ACTIONS = [
    NONE, NORTH, EAST, SOUTH, WEST
]
DIRECTION_MAP = {
    GAME_CONSTANTS['DIRECTIONS']['NORTH']: NORTH,
    GAME_CONSTANTS['DIRECTIONS']['EAST']: EAST,
    GAME_CONSTANTS['DIRECTIONS']['SOUTH']: SOUTH,
    GAME_CONSTANTS['DIRECTIONS']['WEST']: WEST,
    GAME_CONSTANTS['DIRECTIONS']['CENTER']: NONE,
}
REVERSE_MAP = {v: k for k, v in DIRECTION_MAP.items()}

assert len(REVERSE_MAP) == len(DIRECTION_MAP)
